### ISSUE TITLE
Get a dev version hosted on the pythonanywhere server.

### ISSUE THREAD

**Issue by vincentdavis** [vincentdavis/WeRaceHere-Membership#3]
Get a dev version hosted on the pythonanywhere server. You should be able to add another web app.

**Comment by theirfanirfi** [comment]
done.

**Comment by theirfanirfi** [comment]
http://heteroskedastic2.pythonanywhere.com

**Comment by theirfanirfi** [comment]
done. Its the address: http://heteroskedastic2.pythonanywhere.com
